
export const ADD_PRODUCT_TO_CART = `ADD_PRODUCT_TO_CART`
export const ADD_ONE_PRODUCT_TO_CART = 'ADD_ONE_PRODUCT_TO_CART'
export const QUIT_ONE_PRODUCT_FROM_CART = 'QUIT_ONE_PRODUCT_FROM_CART'
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART'